---

- hosts: all
  vars_prompt:
      ssh_keys_install: "Would you like to append this local machine's SSH key as `authorized_key` on the target system? [yes/no]"
  roles:
    - role: ansible-target
    - role: ssh-keys
    - role: zsh
    - role: ansible-util