---

- name: Authorize this host to log in without password on the target machine
  authorized_key: user={{ ansible_ssh_user }} key="{{ lookup('file', '/home/' + ansible_ssh_user + '/.ssh/id_rsa.pub') }}"
  when: ssh_keys_install == 'yes'